name: Release
on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]
  workflow_dispatch:
jobs:
  build_release:
    permissions:
      contents: write
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/build-release-template.yml@main
    with:
      project-name: 'jcdcdev.Umbraco.Core'
      project-path: './src/jcdcdev.Umbraco.Core/jcdcdev.Umbraco.Core.csproj'
      deploy: true
      color-primary: '#5d584d'
      color-secondary: '#73573c'
      color-tertiary: '#aba377'
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}